### ISSUE TITLE
Close old Pull Requests

### ISSUE THREAD

**Issue by rycbar0** [cabaletta/baritone#3687]
Closing outdated, nonsensical, malicious, troll, abandoned Pull requests. There are 43 PRs atm. If you think a abandoned pr should be implemented let me know. i will try to revive it so it can be merged.

PRs:
- [ ] #66 Map Generation - Abandoned for 4 years
- [ ] #244 Bot System - Abandoned for 2.5 Years
- [ ] #283 - Abandoned for 4 years
- [ ] #357 Massive pewfromacnce enhancement - UwU troll
- [ ] #363 backdoor - pretend to be backdoor troll
- [ ] #430 more readable - white space insertion troll
- [ ] #451 Chest sorter - Abandoned for 3 years
- [ ] #598 suspicious pr - python hack script
- [ ] #677 improved goals - troll (makes your account a spawnmason slave)
- [ ] #972 disable support for legacy systems - troll
- [ ] #1064 Go home after mining - Abandoned for 2 years
- [ ] #1706 store in shulker - Abandoned for 2 years
- [x] #1961 avoid block list less hard coded - Abandoned for 2 years
- [ ] #2088 improved mine command - Abandoned for 2 years
- [ ] #2257 ToMap command - Abandoned for 2 years
- [ ] #2430 immersive portal fix - Abandoned for 1.5 years
- [ ] #2484 Add buildAvoidBreakCheck setting - Abandoned for 1.5 years
- [ ] #2527 item following - Abandoned for 8 months

**Comment by wagyourtail** [comment]
No
